# Generated by Django 2.1.1 on 2018-09-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ability',
            field=models.IntegerField(default=0, verbose_name='Habilidade'),
        ),
        migrations.AddField(
            model_name='card',
            name='equipment',
            field=models.IntegerField(default=0, verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='card',
            name='force',
            field=models.IntegerField(default=0, verbose_name='Força'),
        ),
        migrations.AddField(
            model_name='card',
            name='intelligence',
            field=models.IntegerField(default=0, verbose_name='Inteligência'),
        ),
        migrations.AddField(
            model_name='card',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='Velocidade'),
        ),
    ]
