# Generated by Django 2.1.1 on 2018-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunfo', '0004_auto_20180916_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='used',
            field=models.IntegerField(default=0, verbose_name='Status da Carta'),
        ),
    ]
