# Generated by Django 2.1.1 on 2018-09-18 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trunfo', '0005_collection_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('card_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardone', to='trunfo.Collection', verbose_name='Carta Um')),
                ('card_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardtwo', to='trunfo.Collection', verbose_name='Carta Dois')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='trunfo.Game', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Composição',
                'verbose_name_plural': 'Composições',
            },
        ),
    ]
