# Generated by Django 2.1.1 on 2018-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunfo', '0006_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status'),
        ),
    ]
